env:
  es6: true
  node: true
  browser: true
  jest: true
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    legacyDecorators: true
parser: 'babel-eslint'
extends: alchemy
settings:
  react:
    pragma: "React"
    version: "16.8.0"
  import/resolver:
    webpack:
      config: './config/webpack.config.eslint.js'
plugins:
  - react
  - jsx-a11y
  - import
  - jest
  - flowtype
rules:
  no-console:
    - error
    - 'allow':
      - 'warn'
      - 'error'
      - 'info'
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
